# Generated by Django 5.2.7 on 2025-10-03 21:24

import imagekit.models.fields
import inventory.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('slug', models.SlugField()),
                ('highlight_as_new', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('flavor', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hot_drink', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'flavor'],
                'indexes': [models.Index(fields=['name'], name='inventory_d_name_33e774_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'flavor'), name='unique_drink_to_flavor')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('slug', models.SlugField()),
                ('highlight_as_new', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_dessert', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_product')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('slug', models.SlugField()),
                ('highlight_as_new', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('todays_specials', models.BooleanField(default=False)),
                ('drinks', models.ManyToManyField(help_text='Available drinks for the given menu', to='inventory.drink')),
                ('products', models.ManyToManyField(help_text='Available food items for the given menu', to='inventory.product')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_m_name_3ecb0f_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_menu_name')],
            },
        ),
    ]
