# Generated by Django 5.2.7 on 2025-10-03 21:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('total_pre_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_post_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('drinks', models.ManyToManyField(blank=True, to='inventory.drink')),
                ('menus', models.ManyToManyField(to='inventory.menu')),
            ],
            options={
                'ordering': ['-created_on', 'pk'],
                'indexes': [models.Index(fields=['firstname', 'lastname'], name='pickups_pic_firstna_47ae15_idx')],
            },
        ),
    ]
