# Generated by Django 3.2.8 on 2021-11-20 10:01

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import inventory.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('flavor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('todays_specials', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_product'),
        ),
        migrations.AddField(
            model_name='menu',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.drink'),
        ),
        migrations.AddField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(to='inventory.Product'),
        ),
        migrations.AddIndex(
            model_name='drink',
            index=models.Index(fields=['name'], name='inventory_d_name_33e774_idx'),
        ),
        migrations.AddConstraint(
            model_name='drink',
            constraint=models.UniqueConstraint(fields=('name', 'flavor'), name='unique_drink_to_flavor'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['name'], name='inventory_m_name_3ecb0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_menu_name'),
        ),
    ]
