# Generated by Django 3.2.8 on 2021-11-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['name', 'flavor']},
        ),
    ]
