# Generated by Django 4.0.1 on 2022-02-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211121_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_hot_drink',
            field=models.BooleanField(default=False),
        ),
    ]
