# Generated by Django 4.0.1 on 2022-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_drink_highlight_as_new_menu_highlight_as_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='drink',
        ),
        migrations.AddField(
            model_name='menu',
            name='drinks',
            field=models.ManyToManyField(help_text='Available drinks for the given menu', to='inventory.Drink'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(help_text='Available food items for the given menu', to='inventory.Product'),
        ),
    ]
