# Generated by Django 3.2.8 on 2021-10-05 21:31

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import inventory.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('flavor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('todays_specials', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('drinks', models.ManyToManyField(blank=True, to='pickups.Drink')),
                ('menus', models.ManyToManyField(to='pickups.Menu')),
            ],
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['name'], name='pickups_men_name_ee2770_idx'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_menu_name'),
        ),
        migrations.AddIndex(
            model_name='drink',
            index=models.Index(fields=['name'], name='pickups_dri_name_798111_idx'),
        ),
        migrations.AddConstraint(
            model_name='drink',
            constraint=models.UniqueConstraint(fields=('name', 'flavor'), name='unique_drink_to_flavor'),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['firstname', 'lastname'], name='pickups_pic_firstna_47ae15_idx'),
        ),
    ]
