# Generated by Django 3.2.8 on 2021-10-05 21:43

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import inventory.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Image should be higher or equal to 400x400px', upload_to=inventory.utils.upload_to)),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pickups.drink'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='pickups_pro_name_67036d_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_product'),
        ),
        migrations.AddField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(to='pickups.Product'),
        ),
    ]
