# Generated by Django 3.2.8 on 2021-11-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pickups', '0002_auto_20211005_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='products',
        ),
        migrations.AlterField(
            model_name='pickup',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='inventory.Drink'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='menus',
            field=models.ManyToManyField(to='inventory.Menu'),
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
