# Generated by Django 3.2.8 on 2021-11-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0003_auto_20211120_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickup',
            options={'ordering': ['-created_on', 'pk']},
        ),
        migrations.AddField(
            model_name='pickup',
            name='total_post_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pickup',
            name='total_pre_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
